# Site settings
title: Megax
email: megax@yeahunter.hu
username: megax
twittername: JakosaCsaba
description: "Általam készített projektek egy helyen."
baseurl: ""
url: "http://megax.github.io"

# Build settings
markdown: kramdown
permalink: pretty
